# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  working_directory: ~/oc-angularjsTutorial

  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:8-browsers

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        key: oc-angularjsTutorial-{{ .Branch }}-{{ checksum "package.json" }}

        - run: npm install

        - save_cache:
            key: oc-angularjsTutorial-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
            - "node_modules"

        - run: xvfb-run -a npm run test -- --watch=false --progress=false --browsers=ChromeNoSandbox
        #- run: xvfb-run -a npm run e2e -- --config=protractor-ci.conf.js
